#!/usr/bin/env ansible-playbook

#******************************************************************************
# Applikation:          Storage-Admin
# ScriptName:           08_talus_neuen_share_einrichten.yml
# Version:              1.0
# Typ:                  ansible YAML playbook
# Beschreibung:         YAML Playbook Template to start new OnTap Module
#                       based ansible-playbooks
# Author:               Horst Pauli Proffessional Services Consultant
#
# Target Systems:       LINUX Server/VM used as Ansible Host at Customer Site
#
# (C) Copyright         NetApp Switzerland 2020
#******************************************************************************
# Modifications:        01/03/2021      Initial Version         # H. Pauli  ***
#                       xx/xx/xxxx      comment                 # Author    ***
#******************************************************************************

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
  vars_files:
    - global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Automaticaly choose the right Vservername
    set_fact:
      vservername:           "{% if hostname=='tacluster01' %}svm_ta_cifs{% elif hostname=='tbcluster01'%}svm_tb_cifs{% else %}svm_cifs01{% endif %}"

  - name: Create new Windows Share {{ sharename }} on Path {{ pathname }}
    na_ontap_cifs:
      state:                  present
      hostname:               "{{ hostname }}"
      username:               "{{ PRI_CLU_USER }}"
      password:               "{{ PRI_CLU_PASS }}"
      share_name:             "{{ sharename }}"
      path:                   "{{ pathname }}"
      vserver:                "{{ vservername }}"
      share_properties:       browsable,changenotify,oplocks,show-previous-versions,showsnapshot
      symlink_properties:     enable

