#!/usr/bin/env ansible-playbook

#******************************************************************************
# Applikation:          Storage-Admin
# ScriptName:           08_talus_bestehenden_share_loeschen.yml
# Version:              1.0
# Typ:                  ansible YAML playbook
# Beschreibung:         YAML Playbook Template to start new OnTap Module
#                       based ansible-playbooks
# Author:               Horst Pauli Proffessional Services Consultant
#
# Target Systems:       LINUX Server/VM used as Ansible Host at Customer Site
#
# (C) Copyright         NetApp Switzerland 2020
#******************************************************************************
# Modifications:        01/03/2021      Initial Version         # H. Pauli  ***
#                       xx/xx/xxxx      comment                 # Author    ***
#******************************************************************************

- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "{{ PRI_CLU }}"
      username:       "{{ PRI_CLU_USER }}"
      password:       "{{ PRI_CLU_PASS }}"
      https:          true
      validate_certs: false
  vars_files:
    - global.vars
  collections:
    - netapp.ontap

  tasks:
  - name: Create a CIFS Volume on vserver "{{ vservername }}"

